# Set this up, to allow `cargo run` command to run probe-rs-debugger in CLI mode
# TODO: Replace `--chip` and `--speed` values as needed
# TODO: Replace target identifier 
[target.thumbv7em-none-eabihf]
runner = """
probe-rs-debugger
debug
--chip nRF52833_xxAA
--speed 24000
--flashing-enabled
--reset-after-flashing
--program-binary
"""

# TODO: Uncomment for Cortex-M
# TODO: Ensure appropriate `memory.x` linker script is present in the project root folder
rustflags = ["-C", "link-arg=-Tlink.x"]
# TODO: Uncomment for RISCV
# rustflags = ["-C", "link-arg=-Tesp32c3-link.x"]


[build]
# TODO: Replace target identifier 
target = "thumbv7em-none-eabihf"
