[package]
name = "probe-rs-debugger-test"
description = "Test the probe-rs-debugger (and optionally VSCode extension) against various chips/boards"
version = "0.2.0"
authors = ["Jack Noppe <noppej@hotmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[[bin]]
name = "probe-rs-debugger-test"
path = "src/main.rs"

[features]
STM32H745ZITx = []
nRF52833_xxAA = []
RP2040 = []
esp32c3 = []

[target.thumbv6m-none-eabi.dependencies]
cortex-m = { version = "0.7" }
cortex-m-rt = { version = "0.7" }
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-probe = { version = "0.2", features = ["print-rtt"] }

[target.thumbv7em-none-eabihf.dependencies]
cortex-m = { version = "0.7" }
cortex-m-rt = { version = "0.7" }
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-probe = { version = "0.2", features = ["print-rtt"] }

[target.riscv32imac-unknown-none-elf.dependencies]
riscv = { git = "https://github.com/rust-embedded/riscv" }
riscv-rt = { version = "0.8.1" }
# NOTE: We need this very handy atomic-emulation-trap to allow RTT to work on this chip.
riscv-atomic-emulation-trap = { git = "https://github.com/esp-rs/riscv-atomic-emulation-trap", branch = "master" }
panic-halt = { version = "0.2.0" }
rtt-target = { version = "0.3.1", features = ["riscv"] }

[dependencies]
# Dependencies shared between different hardware
heapless = { version = "0.7.9", default-features = false }

[profile.dev]
codegen-units = 1 # better optimizations and easier ELF to debug the debugger
debug = true      # default is `false`; using `true` is also OK as the symbols reside on the host platform, not the target
lto = false       # better optimizations
