[package]
name = "probe-rs-debugger-test"
description = "Test the probe-rs-debugger (and optionally VSCode extension) against various chips/boards"
version = "0.2.0"
authors = ["Jack Noppe <noppej@hotmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[[bin]]
name = "probe-rs-debugger-test"
path = "src/main.rs"

[features]
STM32H745ZITx = []
0483 = []                                             # CONFIGURE: Rename with target PID for your probe
374e = []                                             # CONFIGURE: Rename with target VID for your probe
nRF52833_xxAA = ["nrf52833-hal"]
0d28 = []                                             # CONFIGURE: Rename with target PID for your probe
0204 = []                                             # CONFIGURE: Rename with target VID for your probe
RP2040 = ["embedded-time", "rp-pico", "embedded-hal"]
cafe = []                                             # CONFIGURE: Rename with target PID for your probe
4005 = []                                             # CONFIGURE: Rename with target VID for your probe
esp32c3 = ["esp32c3-hal"]
303a = []                                             # CONFIGURE: Rename with target PID for your probe
1001 = []                                             # CONFIGURE: Rename with target VID for your probe


[target.thumbv6m-none-eabi.dependencies]
cortex-m = { version = "0.7.6" }
cortex-m-rt = { version = "0.7.1" }
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-probe = { version = "0.3", features = ["print-rtt"] }

[target.thumbv7em-none-eabihf.dependencies]
cortex-m = { version = "0.7.6" }
cortex-m-rt = { version = "0.7.1" }
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-probe = { version = "0.3", features = ["print-rtt"] }

# Uncomment this patch to access unreleased (from 0.7.1) feature where prebuilt asm is replaced with inlined asm.
# [patch.crates-io]
# cortex-m-rt = { git = "https://github.com/rust-embedded/cortex-m", branch = "master" }

[target.riscv32imac-unknown-none-elf.dependencies]
riscv = { git = "https://github.com/rust-embedded/riscv" }
riscv-rt = { version = "0.9.0" }
panic-halt = { version = "0.2.0" }
rtt-target = { version = "0.3.1", features = ["riscv"] }
smart-leds = { version = "0.3" }

[dependencies]
# Dependencies shared between different hardware
heapless = { version = "0.7.9", default-features = false }
# Feature specific dependencies
esp32c3-hal = { version = "0.2.0", optional = true, features = [
    "direct-boot",
    "smartled",
] }
embedded-hal = { version = "0.2.7", features = ["unproven"], optional = true }
embedded-time = { version = "0.12.1", optional = true }
nrf52833-hal = { version = "0.15.1", features = ["rt"], optional = true }
rp-pico = { version = "0.5.0", optional = true }

[profile.dev]
codegen-units = 1 # better optimizations and easier ELF to debug the debugger
debug = true      # default is `false`; using `true` is also OK as the symbols reside on the host platform, not the target
lto = false       # better optimizations
