# Set this up, to allow `cargo run` command to run probe-rs-debugger in CLI mode
# TODO: Replace `--chip` and `--speed` values as needed
# TODO: Replace target identifier 
[target.thumbv6m-none-eabi]
runner = """
probe-rs-debugger
debug
--chip RP2040
--speed 24000
--flashing-enabled
--reset-after-flashing
--program-binary
"""

# TODO: Ensure appropriate `memory.x` linker script is present in the project root folder
rustflags = ["-C", "link-arg=-Tlink.x"]


[build]
# TODO: Replace target identifier 
target = "thumbv6m-none-eabi"
