on:
  push:
    branches: [master]
  pull_request:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        run: cargo xtask ci-build

      - name: Store binaries
        uses: actions/upload-artifact@v4
        with:
          name: 'test-binaries'
          path: test-binaries/
          
